### PR TITLE
Updating incorrect defaultProvider value

### PR DESCRIPTION
**Pull request by witheej**

### CODE REVIEW

**Comment by Bitmapped** [comment]
@witheej This isn't really an incorrect value. The value used for the defaultProvider corresponds with the one you want to use on the front-end for authentication. This is normally going to be different than the backoffice provider.

Is there something I'm missing? Please clarify your pull request.

**Comment by witheej** [comment]
There doesn't exist a provider named UmbracoMembershipProvider in this sample code, resulting in this error when it is run:
image

**Comment by Bitmapped** [comment]
Thanks for your feedback. I went a somewhat different direction but have edited the readme documentation to address this issue.

**Comment by witheej** [comment]
Great, thanks for fixing that!

**Pull request closed without merging**
